### ISSUE TITLE
Host the web-based application using GitHub Pages.

### ISSUE THREAD

**Issue by whizdor** [CS455-Assignment-1/stack-n-serve#1]
---
As a **Developer**
I want the web-application to be hosted
So that I may view committed changes incrementally. 

---

**Comment by AditiKhandelia** [comment]
Web-Application hosted at https://cs455-assignment-1.github.io/stack-n-serve/frontend/index.html

**Comment by AditiKhandelia** [comment]
Web-Application hosted at https://cs455-assignment-1.github.io/stack-n-serve/frontend/index.html
